routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|---------------------------------------------------------------
| Admin web routes
|---------------------------------------------------------------
|
| Define routes that starts with /admin/ here
| All routes are already protected with 'auth:admin' middleware
| Don't prefix your routes with `/admin/`
| Don't prefix controllers with `Admin\`
|
*/

Route::get('/', 'DashboardController')->name('dashboard');

Route::get('users/{user}/documents/{document}', 'UserController@downloadDocument')
    ->name('users.documents.show');

Route::resource('users', 'UserController')
    ->only(['index', 'edit', 'update', 'show']);

Route::post('brokers/{broker}/actions/stripe', 'Broker\BrokerActionController@sendStripeInvite')
    ->name('brokers.actions.stripeInvite');

Route::post('brokers/{broker}/report', 'Broker\BrokerController@report')
    ->name('brokers.report');

Route::resource('brokers', 'Broker\BrokerController')
    ->only(['index', 'edit', 'update', 'destroy', 'create', 'store']);

Route::get('brokers/{broker}/download-w9', 'Broker\BrokerController@downloadW9Document')
    ->name('brokers.downloadW9Document');

// User account routes ...
Route::group(['prefix' => 'account', 'as' => 'account.'], function () {
    Route::group(['prefix' => 'password', 'as' => 'password.'], function () {
        Route::get('/', 'Account\PasswordController@edit')->name('edit');
        Route::post('update', 'Account\PasswordController@update')->name('update');
    });

    Route::group(['prefix' => 'actions', 'as' => 'actions.'], function () {
        Route::post('password-reset-email', 'Account\ActionController@sendPasswordResetEmail')
            ->name('passwordResetEmail');
    });
});

// Admin manages other admins
Route::group(['prefix' => 'admins', 'as' => 'admins.', 'namespace' => 'Admin'], function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('create', 'AdminController@create')->name('create');
    Route::post('/', 'AdminController@store')->name('store');
    Route::get('{admin}/edit', 'AdminController@edit')->name('edit');
    Route::put('{admin}', 'AdminController@update')->name('update')
        ->middleware('can:update,admin');
    Route::delete('{admin}', 'AdminController@destroy')->name('destroy')
        ->middleware('can:delete,admin');

    Route::group(['prefix' => 'actions', 'as' => 'actions.'], function () {
        Route::post('{admin}/password-reset-email', 'ActionController@sendPasswordResetEmail')
            ->name('passwordResetEmail');
        Route::patch('{admin}/toggle-block', 'ActionController@toggleBlockedStatus')
            ->name('toggleBlock')->middleware('can:update,admin');
    });
});

Route::resource('services', 'ServiceController')
    ->only(['index', 'edit', 'update', 'destroy', 'create', 'store']);

Route::put('jobs/{job}/cancel', 'Job\ActionController@cancel')
    ->middleware('can:cancel,job')
    ->name('jobs.cancel');

Route::resource('jobs', 'JobController')
    ->only(['index', 'show']);

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([], base_path('routes/guest.php'));

// Realtor dashboard
Route::get('dashboard', 'DashboardController')->middleware(['auth', 'documents.verified'])
    ->name('dashboard');

// Realtor documents
Route::group(['prefix' => 'documents', 'as' => 'documents.', 'middleware' => ['auth']], function () {
    Route::get('/', 'DocumentController@create')->name('create');
    Route::post('store', 'DocumentController@store')->name('store')
        ->middleware('can:create,'.\App\Models\UserDocument::class);
    Route::get('{userDocument}', 'DocumentController@show')->name('show')
        ->middleware('can:view,userDocument');
});

// User account routes
Route::group(['prefix' => 'account', 'as' => 'account.', 'middleware' => ['auth']], function () {

    // My profile
    Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
        Route::get('/', 'Account\ProfileController@edit')->name('edit');

        Route::post('profile', 'Account\ProfileController@update')->name('updateProfile');
    });

    // Change password
    Route::group(['prefix' => 'password', 'as' => 'password.'], function () {
        Route::get('/', 'Account\PasswordController@edit')->name('edit');
        Route::post('update', 'Account\PasswordController@update')->name('update');
    });
});

// User profile
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'middleware' => ['auth']], function () {
    Route::get('{user}', 'ProfileController@show')->name('show');
});

// Job
Route::group(['prefix' => 'jobs', 'as' => 'jobs.', 'middleware' => ['auth', 'documents.verified']], function () {
    Route::get('{job}/detail', 'Job\ShowController@show')->name('show')
        ->middleware('can:view,job');
    Route::get('services', 'Job\CreateController@services')->name('services');
    Route::get('create/{service}', 'Job\CreateController@create')->name('create')
        ->middleware('can:create,'.App\Models\Job::class.',service');
    Route::post('create/{service}', 'Job\CreateController@store')->name('store')
        ->middleware('can:create,'.App\Models\Job::class.',service');
    Route::post('amount/{service}', 'Job\CreateController@getAmount')->name('amount')
        ->middleware('can:create,'.App\Models\Job::class.',service');
    Route::post('{job}/update', 'Job\CreateController@updateIncentive')->name('incentive.update');

    // Job assignment
    Route::group(['prefix' => '{job}/payments', 'as' => 'payments.'], function () {
        Route::get('assign/{user}', 'Job\AssignController@showAssignForm')
            ->name('assign')->middleware('can:assign,job,user');
        Route::post('assign/{user}', 'Job\AssignController@assign')
            ->middleware('can:assign,job,user');
    });

    // Job note
    Route::group(['prefix' => '{job}/chat', 'as' => 'chat.'], function () {
        Route::post('/', 'Job\ChatController@update')->name('update')
            ->middleware('can:update,'.\App\Models\JobChat::class.',job');
        Route::get('/', 'Job\ChatController@index')->name('index')
            ->middleware('can:view,'.\App\Models\JobChat::class.',job');
        Route::get('/{jobChat}/attachment', 'Job\ChatController@downloadAttachment')
            ->name('attachment')->middleware('can:view,'.\App\Models\JobChat::class.',job');
    });

    // Various actions on a Job
    Route::group(['prefix' => 'actions', 'as' => 'actions.'], function () {
        Route::post('{job}/accept', 'Job\ActionController@accept')
            ->name('accept')->middleware('can:accept,job');
        Route::delete('{job}', 'Job\ActionController@delete')
            ->name('destroy')->middleware('can:delete,job');
        Route::post('{job}/ignore', 'Job\ActionController@ignore')
            ->name('ignore');
        Route::post('{job}/done', 'Job\ActionController@markAsDone')
            ->name('done')->middleware('can:markAsDone,job');
        Route::post('{job}/complete', 'Job\ActionController@markAsCompleted')
            ->name('complete')->middleware('can:markAsCompleted,job');
    });
});

// Sent jobs
Route::group(['prefix' => 'sent-jobs', 'as' => 'sentJobs.', 'middleware' => ['auth', 'documents.verified']], function () {
    Route::get('sent', 'SentJobController@sent')->name('sent');
    Route::get('assigned', 'SentJobController@assigned')->name('assigned');
    Route::get('for-review', 'SentJobController@forReview')->name('forReview');
    Route::get('completed', 'SentJobController@completed')->name('completed');
});

// Received jobs
Route::group(['prefix' => 'received-jobs', 'as' => 'receivedJobs.', 'middleware' => ['auth', 'documents.verified']], function () {
    Route::get('received', 'ReceivedJobController@received')->name('received');
    Route::get('accepted', 'ReceivedJobController@accepted')->name('accepted');
    Route::get('to-do', 'ReceivedJobController@toDo')->name('toDo');
    Route::get('completed', 'ReceivedJobController@completed')->name('completed');
});

// Database Notifications
Route::group(['prefix' => 'notifications', 'as' => 'notifications.', 'middleware' => ['auth']], function () {
    Route::get('/', 'NotificationController@index')->name('index');
    Route::delete('delete-all', 'NotificationController@deleteAll')->name('deleteAll');

    Route::post('unread-all', 'NotificationController@markAllAsUnread')->name('markAllAsUnread');
    Route::post('{notification}/unread', 'NotificationController@markAsUnread')->name('markAsUnread');

    Route::post('read-all', 'NotificationController@markAllAsRead')->name('markAllAsRead');
    Route::post('{notification}/read', 'NotificationController@markAsRead')->name('markAsRead');
});

app/Models/Broker.php
<?php

namespace App\Models;

use App\Support\Uploader;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Broker extends Model
{
    use HasFactory;

    protected $guarded = ['id', 'created_at', 'updated_at', 'deleted_at'];

    const STORAGE_DIR = 'broker_documents';

    protected static function boot()
    {
        parent::boot();

        // Delete attached file from storage
        static::deleted(function ($resource) {
            Storage::delete($resource->w9_document);
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function getFullNameAttribute()
    {
        return trim($this->first_name.' '.$this->last_name);
    }

    public function getHasStripeIdAttribute()
    {
        return ! is_null($this->stripe_user_id);
    }

    public function getFullPhoneNumberAttribute()
    {
        return '+1'.$this->area_code.$this->phone;
    }

    public function setW9DocumentAttribute(\Illuminate\Http\UploadedFile $file = null)
    {
        if (is_null($file)) {
            $this->attributes['w9_document'] = null;

            return;
        }
        // Delete old images if any
        // todo find a better way to delete them
        if (! is_null($this->w9_document)) {
            Storage::delete($this->w9_document);
        }

        $this->attributes['w9_document'] = Storage::putFile(Uploader::dirPath(self::STORAGE_DIR), $file, 'private');
    }

    public function downloadW9Document($headers = [])
    {
        abort_unless(Storage::exists($this->w9_document), 404);

        $fileParts = explode('.', $this->w9_document);
        $documentName = 'w9-document'.'.'.last($fileParts);

        return Storage::download($this->w9_document, $documentName, $headers);
    }
}

resources/views/dashboard.blade.php
@extends('_layouts.app')
@section('pageTitle','Dashboard')

@section('content')

  <section class="dashboard-in">
    <div class="container">
      @component('components.breadcrumb')
        Dashboard
      @endcomponent

      <section class="row">
        <div class="col-sm-6">
          <div class="sent-jobs">
            <h3>
              Sent Jobs
              <span class="dots-large"></span>
              <span class="dots-small"></span>
              <span class="dots-ex-small"></span>
            </h3>
            <div class="row text-center">
              <div class="col">
                <div class="job-value">{{$counts->sent_jobs}}</div>
                <a href="{{route('sentJobs.sent')}}" class="btn btn-bordered">Sent</a>
              </div>
              <div class="col">
                <div class="job-value">{{$counts->assigned_jobs}}</div>
                <a href="{{route('sentJobs.assigned')}}" class="btn btn-bordered">Assigned</a>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-6">
          <div class="received-jobs">
            <h3>
              Received Jobs
              <span class="dots-large"></span>
              <span class="dots-small"></span>
              <span class="dots-ex-small"></span>
            </h3>
            <div class="row text-center">
              <div class="col">
                <div class="job-value">{{$counts->received_jobs}}</div>
                <a href="{{route('receivedJobs.received')}}" class="btn btn-bordered">Received</a>
              </div>
              <div class="col">
                <div class="job-value">{{$counts->accepted_jobs}}</div>
                <a href="{{route('receivedJobs.accepted')}}" class="btn btn-bordered">Accepted</a>
              </div>
            </div>
          </div>
        </div>
      </section>

      <received-jobs-card :jobs='@json($receivedJobs)'></received-jobs-card>
      <sent-jobs-card :jobs='@json($sentJobs)'></sent-jobs-card>
      <upcoming-jobs-card :jobs='@json($upcomingJobs)'></upcoming-jobs-card>
    </div>
  </section>
  <job-accept-modal></job-accept-modal>
  <job-ignore-modal></job-ignore-modal>
  <job-done-modal></job-done-modal>
  <job-delete-modal></job-delete-modal>
@endsection

resources/views/profile.blade.php
@extends('_layouts.app')
@section('pageTitle','Profile')

@section('content')
  <div class="container mid-section view-profile">

    <section class="card-white text-center">
      @if(auth('web')->user()->is($user))
        <a href="{{route('account.profile.edit')}}" class="btn-edit">
          <i class="fas fa-pen fa-lg"></i>
        </a>
      @endif
      <div class="img-round round-big">
        <img src="{{$user->profile->avatar_thumb_url}}" alt="avatar">
      </div>
      <h3 class="mt-5">{{$user->profile->full_name}}</h3>
      <p>Company Name: {{$user->broker->company_name}}</p>
      <div class="stars">
        @foreach(range(1,5) as $rating)
          @if($loop->iteration <= (int)$user->rating)
            <i class="fas fa-star text-warning"></i>
          @else
            <i class="fas fa-star text-muted"></i>
          @endif
        @endforeach
      </div>
      <div class="col-md-8 offset-md-2 mt-5">
        <p>{{$user->profile->bio}}</p>
      </div>
    </section>

    <section class="card-white">
      <h4>Accomplishments</h4>
      @foreach($accomplishments as $item)
        <div
          class="profile-item">{{$item->total}} {{$item->service->name}} {{\Illuminate\Support\Str::plural('Job',$item->total)}}
          done successfully.
        </div>
      @endforeach
    </section>

    <section class="card-white">
      <h4>Services</h4>
      <div class="profile-item">
        <h4>
          @foreach($user->services as $item)
            <span class="badge badge-pill badge-secondary">{{$item->name}}</span>
          @endforeach
        </h4>
      </div>
    </section>

    <section class="card-white">
      <h4>Work Cities</h4>
      <div class="profile-item">
        <h4>
          @foreach($user->cities as $item)
            <span class="badge badge-pill badge-secondary mb-3">{{$item->name}}</span>
          @endforeach
        </h4>
      </div>
    </section>

    <section class="card-white">
      <h4>Background</h4>
      <div class="profile-item">
        <strong>Education</strong>
        <p>{{$user->profile->education}}</p>
      </div>
      <div class="profile-item">
        <strong>Experience</strong>
        <p>{{$user->profile->experience}}</p>
      </div>
    </section>

    <section class="card-white contact-info">
      <h4>Contact Information</h4>
      <div class="profile-item">
        <strong>Area code</strong>
        <span>@if($user->address->area_code)(+1){{$user->address->area_code}}@endif</span>
      </div>
      <div class="profile-item">
        <strong>Phone</strong>
        <span>{{$user->address->primary_phone}}</span>
      </div>
      <div class="profile-item">
        <strong>Email</strong>
        <span>{{$user->email}}</span>
      </div>
      <div class="profile-item">
        <strong>City</strong>
        <span>{{$user->address->city}}</span>
      </div>
      <div class="profile-item">
        <strong>State</strong>
        <span>{{$user->address->state}}</span>
      </div>
      <div class="profile-item">
        <strong>Address</strong>
        <span>{{$user->address->street_address}}</span>
      </div>
    </section>

    @if(auth('web')->user()->is($user))
      <section class="card-white contact-info">
        <h4>Broker Information</h4>
        <div class="profile-item">
          <strong>Name</strong>
          <span>{{$user->broker->full_name}}</span>
        </div>
        <div class="profile-item">
          <strong>Phone</strong>
          <span>{{$user->broker->phone}}</span>
        </div>
        <div class="profile-item">
          <strong>Email</strong>
          <span>{{$user->broker->email}}</span>
        </div>
      </section>
    @endif

  </div>
@endsection

resources/views/stripeConnectStatus.blade.php
@extends('_layouts.app')
@section('pageTitle','Stripe Connect')

@section('content')
  @include('_partials.logo')

  <div class="form-wrap">
    @include('alert::bootstrap')

    <div class="text-center">
      @if (session('status'))
        <i class="fas fa-8x fa-check-circle text-success my-5"></i>
        <h3 class="h1">Stripe connect was successful.</h3>
      @elseif(session('error'))
        <i class="fas fa-8x fa-times-circle text-danger my-5"></i>
        <h3 class="h1">{{session('error')}}</h3>
        <p>Try again or contact administrator if problem persist.</p>
      @endif
    </div>
  </div>

@endsection