routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|---------------------------------------------------------------
| Admin web routes
|---------------------------------------------------------------
|
| Define routes that starts with /admin/ here
| All routes are already protected with 'auth:admin' middleware
| Don't prefix your routes with `/admin/`
| Don't prefix controllers with `Admin\`
|
*/

Route::get('/', 'DashboardController')->name('dashboard');

Route::get('users/{user}/documents/{document}', 'UserController@downloadDocument')
    ->name('users.documents.show');

Route::resource('users', 'UserController')
    ->only(['index', 'edit', 'update', 'show']);

Route::post('brokers/{broker}/actions/stripe', 'Broker\BrokerActionController@sendStripeInvite')
    ->name('brokers.actions.stripeInvite');

Route::post('brokers/{broker}/report', 'Broker\BrokerController@report')
    ->name('brokers.report');

Route::resource('brokers', 'Broker\BrokerController')
    ->only(['index', 'edit', 'update', 'destroy', 'create', 'store']);

Route::get('brokers/{broker}/download-w9', 'Broker\BrokerController@downloadW9Document')
    ->name('brokers.downloadW9Document');

// User account routes ...
Route::group(['prefix' => 'account', 'as' => 'account.'], function () {
    Route::group(['prefix' => 'password', 'as' => 'password.'], function () {
        Route::get('/', 'Account\PasswordController@edit')->name('edit');
        Route::post('update', 'Account\PasswordController@update')->name('update');
    });

    Route::group(['prefix' => 'actions', 'as' => 'actions.'], function () {
        Route::post('password-reset-email', 'Account\ActionController@sendPasswordResetEmail')
            ->name('passwordResetEmail');
    });
});

// Admin manages other admins
Route::group(['prefix' => 'admins', 'as' => 'admins.', 'namespace' => 'Admin'], function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('create', 'AdminController@create')->name('create');
    Route::post('/', 'AdminController@store')->name('store');
    Route::get('{admin}/edit', 'AdminController@edit')->name('edit');
    Route::put('{admin}', 'AdminController@update')->name('update')
        ->middleware('can:update,admin');
    Route::delete('{admin}', 'AdminController@destroy')->name('destroy')
        ->middleware('can:delete,admin');

    Route::group(['prefix' => 'actions', 'as' => 'actions.'], function () {
        Route::post('{admin}/password-reset-email', 'ActionController@sendPasswordResetEmail')
            ->name('passwordResetEmail');
        Route::patch('{admin}/toggle-block', 'ActionController@toggleBlockedStatus')
            ->name('toggleBlock')->middleware('can:update,admin');
    });
});

Route::resource('services', 'ServiceController')
    ->only(['index', 'edit', 'update', 'destroy', 'create', 'store']);

Route::put('jobs/{job}/cancel', 'Job\ActionController@cancel')
    ->middleware('can:cancel,job')
    ->name('jobs.cancel');

Route::resource('jobs', 'JobController')
    ->only(['index', 'show']);

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([], base_path('routes/guest.php'));

// Realtor dashboard
Route::get('dashboard', 'DashboardController')->middleware(['auth', 'documents.verified'])
    ->name('dashboard');

// Realtor documents
Route::group(['prefix' => 'documents', 'as' => 'documents.', 'middleware' => ['auth']], function () {
    Route::get('/', 'DocumentController@create')->name('create');
    Route::post('store', 'DocumentController@store')->name('store')
        ->middleware('can:create,'.\App\Models\UserDocument::class);
    Route::get('{userDocument}', 'DocumentController@show')->name('show')
        ->middleware('can:view,userDocument');
});

// User account routes
Route::group(['prefix' => 'account', 'as' => 'account.', 'middleware' => ['auth']], function () {

    // My profile
    Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
        Route::get('/', 'Account\ProfileController@edit')->name('edit');

        Route::post('profile', 'Account\ProfileController@update')->name('updateProfile');
    });

    // Change password
    Route::group(['prefix' => 'password', 'as' => 'password.'], function () {
        Route::get('/', 'Account\PasswordController@edit')->name('edit');
        Route::post('update', 'Account\PasswordController@update')->name('update');
    });
});

// User profile
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'middleware' => ['auth']], function () {
    Route::get('{user}', 'ProfileController@show')->name('show');
});

// Job
Route::group(['prefix' => 'jobs', 'as' => 'jobs.', 'middleware' => ['auth', 'documents.verified']], function () {
    Route::get('{job}/detail', 'Job\ShowController@show')->name('show')
        ->middleware('can:view,job');
    Route::get('services', 'Job\CreateController@services')->name('services');
    Route::get('create/{service}', 'Job\CreateController@create')->name('create')
        ->middleware('can:create,'.App\Models\Job::class.',service');
    Route::post('create/{service}', 'Job\CreateController@store')->name('store')
        ->middleware('can:create,'.App\Models\Job::class.',service');
    Route::post('amount/{service}', 'Job\CreateController@getAmount')->name('amount')
        ->middleware('can:create,'.App\Models\Job::class.',service');
    Route::post('{job}/update', 'Job\CreateController@updateIncentive')->name('incentive.update');

    // Job assignment
    Route::group(['prefix' => '{job}/payments', 'as' => 'payments.'], function () {
        Route::get('assign/{user}', 'Job\AssignController@showAssignForm')
            ->name('assign')->middleware('can:assign,job,user');
        Route::post('assign/{user}', 'Job\AssignController@assign')
            ->middleware('can:assign,job,user');
    });

    // Job note
    Route::group(['prefix' => '{job}/chat', 'as' => 'chat.'], function () {
        Route::post('/', 'Job\ChatController@update')->name('update')
            ->middleware('can:update,'.\App\Models\JobChat::class.',job');
        Route::get('/', 'Job\ChatController@index')->name('index')
            ->middleware('can:view,'.\App\Models\JobChat::class.',job');
        Route::get('/{jobChat}/attachment', 'Job\ChatController@downloadAttachment')
            ->name('attachment')->middleware('can:view,'.\App\Models\JobChat::class.',job');
    });

    // Various actions on a Job
    Route::group(['prefix' => 'actions', 'as' => 'actions.'], function () {
        Route::post('{job}/accept', 'Job\ActionController@accept')
            ->name('accept')->middleware('can:accept,job');
        Route::delete('{job}', 'Job\ActionController@delete')
            ->name('destroy')->middleware('can:delete,job');
        Route::post('{job}/ignore', 'Job\ActionController@ignore')
            ->name('ignore');
        Route::post('{job}/done', 'Job\ActionController@markAsDone')
            ->name('done')->middleware('can:markAsDone,job');
        Route::post('{job}/complete', 'Job\ActionController@markAsCompleted')
            ->name('complete')->middleware('can:markAsCompleted,job');
    });
});

// Sent jobs
Route::group(['prefix' => 'sent-jobs', 'as' => 'sentJobs.', 'middleware' => ['auth', 'documents.verified']], function () {
    Route::get('sent', 'SentJobController@sent')->name('sent');
    Route::get('assigned', 'SentJobController@assigned')->name('assigned');
    Route::get('for-review', 'SentJobController@forReview')->name('forReview');
    Route::get('completed', 'SentJobController@completed')->name('completed');
});

// Received jobs
Route::group(['prefix' => 'received-jobs', 'as' => 'receivedJobs.', 'middleware' => ['auth', 'documents.verified']], function () {
    Route::get('received', 'ReceivedJobController@received')->name('received');
    Route::get('accepted', 'ReceivedJobController@accepted')->name('accepted');
    Route::get('to-do', 'ReceivedJobController@toDo')->name('toDo');
    Route::get('completed', 'ReceivedJobController@completed')->name('completed');
});

// Database Notifications
Route::group(['prefix' => 'notifications', 'as' => 'notifications.', 'middleware' => ['auth']], function () {
    Route::get('/', 'NotificationController@index')->name('index');
    Route::delete('delete-all', 'NotificationController@deleteAll')->name('deleteAll');

    Route::post('unread-all', 'NotificationController@markAllAsUnread')->name('markAllAsUnread');
    Route::post('{notification}/unread', 'NotificationController@markAsUnread')->name('markAsUnread');

    Route::post('read-all', 'NotificationController@markAllAsRead')->name('markAllAsRead');
    Route::post('{notification}/read', 'NotificationController@markAsRead')->name('markAsRead');
});

app/Models/Broker.php
<?php

namespace App\Models;

use App\Support\Uploader;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Broker extends Model
{
    use HasFactory;

    protected $guarded = ['id', 'created_at', 'updated_at', 'deleted_at'];

    const STORAGE_DIR = 'broker_documents';

    protected static function boot()
    {
        parent::boot();

        // Delete attached file from storage
        static::deleted(function ($resource) {
            Storage::delete($resource->w9_document);
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function getFullNameAttribute()
    {
        return trim($this->first_name.' '.$this->last_name);
    }

    public function getHasStripeIdAttribute()
    {
        return ! is_null($this->stripe_user_id);
    }

    public function getFullPhoneNumberAttribute()
    {
        return '+1'.$this->area_code.$this->phone;
    }

    public function setW9DocumentAttribute(\Illuminate\Http\UploadedFile $file = null)
    {
        if (is_null($file)) {
            $this->attributes['w9_document'] = null;

            return;
        }
        // Delete old images if any
        // todo find a better way to delete them
        if (! is_null($this->w9_document)) {
            Storage::delete($this->w9_document);
        }

        $this->attributes['w9_document'] = Storage::putFile(Uploader::dirPath(self::STORAGE_DIR), $file, 'private');
    }

    public function downloadW9Document($headers = [])
    {
        abort_unless(Storage::exists($this->w9_document), 404);

        $fileParts = explode('.', $this->w9_document);
        $documentName = 'w9-document'.'.'.last($fileParts);

        return Storage::download($this->w9_document, $documentName, $headers);
    }
}

app/Http/Controllers/Admin/Job/ActionController.php
<?php

namespace App\Http\Controllers\Admin\Job;

use App\Http\Controllers\Controller;
use App\Models\Job;
use App\Models\Refund;
use App\Notifications\JobCancelled;
use App\Notifications\RefundOnJobCancelled;
use App\Support\Money;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\DB;

class ActionController extends Controller
{
    public function cancel(Request $request, Job $job)
    {
        $this->validate($request, [
            'cancellation_reason' => ['required', 'string', 'min:3', 'max:1000'],
        ]);

        DB::beginTransaction();

        $refund = $this->processRefund($job);

        $job->setStatusTo(Job::STATUS_CANCELLED);
        $job->fill([
            'cancelled_at' => Date::now(),
            'cancellation_reason' => $request->input('cancellation_reason'),
        ]);
        $job->save();

        DB::commit();

        $job->assignee->notify(new JobCancelled($job));
        $job->creator->notify(new RefundOnJobCancelled($job, $refund));

        alert()->success('Job was cancelled.');

        return redirect()->route('admin.jobs.index');
    }

    protected function processRefund(Job $job): Refund
    {
        $charge = $job->charge;

        $response = \Stripe\Refund::create([
            'charge' => $charge->transaction_id,
            'reason' => 'requested_by_customer',
            'metadata' => [
                'jobId' => $job->getKey(),
            ],
        ]);

        $refund = new Refund();
        $refund->charge()->associate($charge);
        $refund->fill([
            'transaction_id' => $response->id,
            'total_amount' => Money::centsToDollars($response->amount),
        ]);
        $refund->save();

        return $refund;
    }
}

app/Http/Controllers/Admin/JobController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\City;
use App\Models\Job;
use Illuminate\Http\Request;

class JobController extends Controller
{
    /**
     * Display a listing of the jobs.
     *
     * @param  Request $request
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $cities = City::all();

        $jobs = Job::query()
            ->with(['service', 'creator.profile', 'assignee.profile', 'charge', 'transfer'])
            ->orderByDesc('updated_at');

        if ($request->filled('search')) {
            $jobs->whereHas('service', function ($query) use ($request) {
                $query->where('name', 'like', '%'.$request->input('search').'%');
            });

            $jobs->orWhereHas('creator.profile', function ($query) use ($request) {
                $query->where('first_name', 'like', '%'.$request->input('search').'%')
                    ->orWhere('last_name', 'like', '%'.$request->input('search').'%');
            });

            $jobs->orWhereHas('assignee.profile', function ($query) use ($request) {
                $query->where('first_name', 'like', '%'.$request->input('search').'%')
                    ->orWhere('last_name', 'like', '%'.$request->input('search').'%');
            });
        }

        if ($request->filled('job_status')) {
            $jobs->where('status', $request->input('job_status'));
        }

        if ($request->filled('city_id')) {
            $jobs->whereHas('cities', function ($query) use ($request) {
                $query->where('cities.id', $request->input('city_id'));
            });
        }

        $jobs = $jobs->latest()
            ->paginate($request->input('per_page', 10));

        return view('admin.jobs.index', compact('jobs', 'cities'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Job $job
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Job $job)
    {
        $job->loadMissing(['creator.profile', 'cities']);

        if ($job->assignee_user_id) {
            $job->loadMissing(['assignee.profile']);
        } else {
            $job->loadMissing(['applicants.profile', 'applicants.assessments']);
        }

        return view('admin.jobs.show', compact('job'));
    }
}

app/Http/Controllers/Job/ChatController.php
<?php

namespace App\Http\Controllers\Job;

use App\Http\Controllers\Controller;
use App\Http\Requests\Job\ChatRequest;
use App\Models\Job;
use App\Models\JobChat;
use Illuminate\Support\Facades\Date;

class ChatController extends Controller
{
    /**
     * Get chats for a job.
     *
     * @param  Job  $job
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index(Job $job)
    {
        $chats = $job->chat()->orderByDesc('created_at')->paginate(10);

        $this->markReadBeforeSend($chats);

        $chats->load(['user', 'user.profile']);

        return response()->json($chats);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  ChatRequest  $request
     * @param  Job  $job
     *
     * @return \Illuminate\Http\JsonResponse
     * @throws \Exception
     */
    public function update(ChatRequest $request, Job $job)
    {
        $chat = JobChat::create(
            [
                'job_id' => $job->getKey(),
                'sender_id' => $request->user()->getKey(),
                'message' => $request->input('message'),
                'attachment' => $request->file('attachment'),
            ]
        );

        if ($job->creator->is($request->user())) {
            $job->assignee->notify(new \App\Notifications\JobChatReceived($job, $job->creator));
        } else {
            $job->creator->notify(new \App\Notifications\JobChatReceived($job, $job->assignee));
        }

        $chat->load(['user.profile']);

        return response()->json($chat);
    }

    /**
     * @param  Job  $job
     *
     * @param  JobChat  $jobChat
     *
     * @return mixed
     */
    public function downloadAttachment(Job $job, JobChat $jobChat)
    {
        return $jobChat->downloadAttachmentFile();
    }

    public function markReadBeforeSend($chats)
    {
        $unread = array_filter($chats->items(), function ($item) {
            return is_null($item['read_at']);
        });

        if (! count($unread)) {
            return false;
        }

        return JobChat::query()
            ->where('sender_id', '<>', auth()->user()->getKey())
            ->whereIn('id', array_column($unread, 'id'))
            ->update(['read_at' => Date::now()]);
    }
}

resources/views/admin/jobs/_cancelForm.blade.php
<form method="post" action="{{route('admin.jobs.cancel', $job)}}" onsubmit="return confirm('Are you sure to cancel?')">
  @csrf
  @method('put')
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title">Cancel job</h5>
      <div class="form-group required mb-0">
        <label>Cancellation reason</label>
        <textarea class="form-control @isInvalid('cancellation_reason')"
                  name="cancellation_reason"
                  rows="2">{{ old('cancellation_reason', $job->cancellation_reason) }}</textarea>
        @validationMessage('cancellation_reason')
      </div>
    </div>
    <div class="card-footer text-right">
      <div class="d-inline-block text-muted mr-3">
        Realtor will receive a refund.
      </div>
      <button class="btn btn-danger" type="submit">
        <i class="fas fa-fw fa-times-circle"></i> Cancel the job
      </button>
    </div>
  </div>
</form>

resources/views/admin/jobs/index.blade.php
@extends('admin._layouts.admin')
@section('pageTitle','Jobs')

@section('content')

  @component('admin.components.breadcrumb')
    Jobs
  @endcomponent

  @include('alert::bootstrap')

  <section class="card mb-3">
    <div class="card-body">
      <form id="search-form" class="form-inline" method="GET" action="{{route('admin.jobs.index')}}">
        <select class="form-control mb-2 mb-sm-0 mr-sm-2" name="per_page">
          <option disabled>Per page</option>
          @foreach([10,30,50] as $perPage)
            <option value="{{$perPage}}"
                    @if(request('per_page') == $perPage) selected @endif>{{$perPage}}</option>
          @endforeach
        </select>

        <select class="form-control mb-2 mb-sm-0 mr-sm-2 text-capitalize" name="job_status">
          <option disabled>Job status</option>
          <option value="">Any</option>
          @foreach(['completed' ,'pending', 'done', 'cancelled'] as $status)
            <option value="{{$status}}"
                    @if(request('job_status') === $status) selected @endif>{{$status}}</option>
          @endforeach
        </select>

        <select class="form-control mb-2 mb-sm-0 mr-sm-2 text-capitalize" name="city_id">
          <option disabled>Cities</option>
          <option value="">All</option>
          @foreach($cities as $city)
            <option value="{{$city->id}}"
                    @if(request('city_id') == $city->id) selected @endif>{{$city->name}}</option>
          @endforeach
        </select>

        <input type="text" class="form-control mb-2 mb-sm-0 mr-sm-2" placeholder="Search" name="search"
               value="{{request('search')}}" autofocus>

        <button type="submit" class="btn btn-primary mb-0 mb-sm-0 mr-sm-2">
          <i class="fa fa-search fa-fw"></i>Search
        </button>
      </form>
    </div>
  </section>

  <section class="table-responsive mb-3">
    <table class="table table-striped  table-bordered table-hover">
      <thead>
      <tr>
        <th>Service Name</th>
        <th>Creator Name</th>
        <th>Assignee Name</th>
        <th>Chargeable Amount</th>
        <th>Transferable Amount</th>
        <th>Due Date</th>
        <th>Posted at</th>
        <th>Status</th>
      </tr>
      </thead>
      <tbody>
      @forelse($jobs as $job)
        <tr>
          <td>
            <a href="{{route('admin.jobs.show',$job)}}">
              {{$job->service->name}}
            </a>
          </td>
          <td data-id="{{$job->creator->id}}">
            <a href="{{route('admin.users.show',$job->creator)}}">
              {{$job->creator->profile->full_name}}
            </a>
          </td>
          <td>
            @if($job->assignee)
              <a href="{{route('admin.users.show',$job->assignee)}}">
                {{$job->assignee->profile->full_name}}
              </a>
            @endif
          </td>
          <td>${{$job->chargeable_amount + $job->chargeable_incentive_amount}}</td>
          <td>${{$job->transferable_amount + $job->transferable_incentive_amount}}</td>
          <td>@date($job->due_date)</td>
          <td>@date($job->created_at)</td>
          <td class="align-middle h5">
            @switch($job->status)
              @case(\App\Models\Job::STATUS_COMPLETED)
              <span class="badge badge-success">Completed</span>
              @break
              @case(\App\Models\Job::STATUS_DONE)
              <span class="badge badge-warning">Done</span>
              @break
              @case(\App\Models\Job::STATUS_PENDING)
              <span class="badge badge-secondary">Pending</span>
              @break
              @case(\App\Models\Job::STATUS_CANCELLED)
              <span class="badge badge-danger">Cancelled</span>
              @break
            @endswitch
          </td>
        </tr>
      @empty
        <tr>
          <td colspan="8" class="text-center">No records found</td>
        </tr>
      @endforelse
      </tbody>
    </table>
  </section>

  @if($jobs->total() > 0)
    <div class="row">
      <div class="col-md-4 mb-sm-0 mb-3 text-center text-sm-left">
        <h5 class="mt-sm-2 mt-0 mb-0">Found {{$jobs->total()}} entries</h5>
      </div>
      <div class="col-md-8 d-flex">
        <div class="mx-auto ml-sm-auto mr-sm-0 table-responsive-sm">
          {{$jobs->appends(request()->query())->links()}}
        </div>
      </div>
    </div>
  @endif
@endsection

resources/views/admin/jobs/show.blade.php
@extends('admin._layouts.admin')
@section('pageTitle','View Job Details')

@section('content')

  @component('admin.components.breadcrumb',[
        'links' => [
          'jobs' => route('admin.jobs.index')
        ]
      ])
    Details
  @endcomponent

  @include('alert::bootstrap')

  <div class="row mb-3">
    <aside class="col-md-3">
      <div class="card mb-3">
        <div class="card-body text-center">
          @if($job->creator->profile->avatar)
            <a href="{{$job->creator->profile->avatar_thumb_url}}" target="_blank">
              <img class="img-thumbnail rounded" src="{{$job->creator->profile->avatar_thumb_url}}" alt="avatar"
                   width="300">
              <span class="sr-only">View large image</span>
            </a>
          @else
            <i class="fas fa-8x fa-user-circle text-muted"></i>
          @endif
          <p class="h5 my-3 text-truncate"><strong>Creator:</strong> {{$job->creator->profile->full_name}}</p>
          <p class="my-3 text-truncate">{{$job->creator->email}}</p>
        </div>
      </div>

      <div class="card mb-3">
        @if($job->assignee)
          <div class="card-body text-center">
            @if($job->assignee->profile->avatar)
              <a href="{{$job->assignee->profile->avatar_thumb_url}}" target="_blank">
                <img class="img-thumbnail rounded" src="{{$job->assignee->profile->avatar_thumb_url}}" alt="avatar"
                     width="300">
                <span class="sr-only">View large image</span>
              </a>
            @else
              <i class="fas fa-8x fa-user-circle text-muted"></i>
            @endif
            <p class="h5 my-3 text-truncate"><strong>Assignee:</strong> {{$job->assignee->profile->full_name}}</p>
            <p class="my-3 text-truncate">{{$job->assignee->email}}</p>
          </div>
        @else
          <div class="card-body no-record p-5">
            <h3 class="text-muted">No realtor assigned yet.</h3>
          </div>
        @endif
      </div>
    </aside>

    <section class="col-md-9 mt-sm-0 mt-lg-0 mt-4">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title">Job Details</h5>
          <table class="table table-bordered">
            <tbody>
            <tr>
              <td><strong>Service Name</strong></td>
              <td>{{$job->service->name}}</td>
            </tr>
            <tr>
              <td><strong>City</strong></td>
              <td>
                @foreach($job->cities as $item)
                  <span class="badge badge-pill badge-secondary font-weight-normal">{{$item->name}}</span>
                @endforeach
              </td>
            </tr>
            <tr>
              <td><strong>Job Description</strong></td>
              <td>@if($job->description){{$job->description}}@else - @endif</td>
            </tr>
            <tr>
              <td><strong>Chargeable Amount</strong></td>
              <td>${{$job->chargeable_amount + $job->chargeable_incentive_amount}}</td>
            </tr>
            <tr>
              <td><strong>Transferable Amount</strong></td>
              <td>${{$job->transferable_amount + $job->transferable_incentive_amount}}</td>
            </tr>
            <tr>
              <td><strong>Incentive Amount</strong></td>
              <td>@if($job->transferable_incentive_amount)${{$job->transferable_incentive_amount}}@else $0 @endif</td>
            </tr>
            <tr>
              <td><strong>Posted at</strong></td>
              <td>@date($job->created_at)</td>
            </tr>
            <tr>
              <td><strong>Due Date</strong></td>
              <td>@date($job->due_date)</td>
            </tr>
            <tr>
              <td><strong>Status</strong></td>
              <td>
                @switch($job->status)
                  @case(\App\Models\Job::STATUS_COMPLETED)
                  <span class="badge badge-success">Completed</span>
                  @break
                  @case(\App\Models\Job::STATUS_DONE)
                  <span class="badge badge-warning">Done</span>
                  @break
                  @case(\App\Models\Job::STATUS_PENDING)
                  <span class="badge badge-secondary">Pending</span>
                  @break
                  @case(\App\Models\Job::STATUS_CANCELLED)
                  <span class="badge badge-danger">Cancelled</span>
                  @break
                @endswitch
              </td>
            </tr>
            @if($job->cancelled_at)
              <tr>
                <td><b>Cancelled at</b></td>
                <td>@date($job->cancelled_at)</td>
              </tr>
              <tr>
                <td><b>Cancellation reason</b></td>
                <td>{{$job->cancellation_reason}}</td>
              </tr>
            @endif
            </tbody>
          </table>
        </div>
      </div>

      @if(!$job->assignee_user_id)
        <div class="card mb-3">
          <div class="card-body">
            <h5 class="card-title">Offer Accepted by - {{$job->applicants->count()}}</h5>
            @forelse($job->applicants as $applicant)
              <div class="d-flex mb-3">
                <div>
                  <img src="{{$applicant->profile->avatar_thumb_url}}" class="rounded-circle" alt="avatar" width="100"
                       height="100">
                </div>
                <div class="w-100 pl-3 my-auto">
                  <div class="row">
                    <div class="col-sm-12 col-md-8">
                      <h5>{{ $applicant->profile->full_name }}</h5>
                      <div class="stars mb-2">
                        @foreach(range(1,5) as $rating)
                          @if($loop->iteration <= (int)$applicant->rating)
                            <i class="fas fa-star text-warning"></i>
                          @else
                            <i class="fas fa-star text-muted"></i>
                          @endif
                        @endforeach
                      </div>
                      <h6><a href="{{route('admin.users.show',$applicant)}}" target="_blank">View Profile</a></h6>
                    </div>
                  </div>
                </div>
              </div>
            @empty
              <div class="text-center text-muted">No applicant yet.</div>
            @endforelse
          </div>
        </div>
      @endif

      @can('cancel', $job)
        @include('admin.jobs._cancelForm')
      @endcan
    </section>
  </div>

@endsection