routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|---------------------------------------------------------------
| Admin web routes
|---------------------------------------------------------------
|
| Define routes that starts with /admin/ here
| All routes are already protected with 'auth:admin' middleware
| Don't prefix your routes with `/admin/`
| Don't prefix controllers with `Admin\`
|
*/

Route::get('/', 'DashboardController')->name('dashboard');

Route::get('users/{user}/documents/{document}', 'UserController@downloadDocument')
    ->name('users.documents.show');

Route::resource('users', 'UserController')
    ->only(['index', 'edit', 'update', 'show']);

Route::post('brokers/{broker}/actions/stripe', 'Broker\BrokerActionController@sendStripeInvite')
    ->name('brokers.actions.stripeInvite');

Route::post('brokers/{broker}/report', 'Broker\BrokerController@report')
    ->name('brokers.report');

Route::resource('brokers', 'Broker\BrokerController')
    ->only(['index', 'edit', 'update', 'destroy', 'create', 'store']);

Route::get('brokers/{broker}/download-w9', 'Broker\BrokerController@downloadW9Document')
    ->name('brokers.downloadW9Document');

// User account routes ...
Route::group(['prefix' => 'account', 'as' => 'account.'], function () {
    Route::group(['prefix' => 'password', 'as' => 'password.'], function () {
        Route::get('/', 'Account\PasswordController@edit')->name('edit');
        Route::post('update', 'Account\PasswordController@update')->name('update');
    });

    Route::group(['prefix' => 'actions', 'as' => 'actions.'], function () {
        Route::post('password-reset-email', 'Account\ActionController@sendPasswordResetEmail')
            ->name('passwordResetEmail');
    });
});

// Admin manages other admins
Route::group(['prefix' => 'admins', 'as' => 'admins.', 'namespace' => 'Admin'], function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('create', 'AdminController@create')->name('create');
    Route::post('/', 'AdminController@store')->name('store');
    Route::get('{admin}/edit', 'AdminController@edit')->name('edit');
    Route::put('{admin}', 'AdminController@update')->name('update')
        ->middleware('can:update,admin');
    Route::delete('{admin}', 'AdminController@destroy')->name('destroy')
        ->middleware('can:delete,admin');

    Route::group(['prefix' => 'actions', 'as' => 'actions.'], function () {
        Route::post('{admin}/password-reset-email', 'ActionController@sendPasswordResetEmail')
            ->name('passwordResetEmail');
        Route::patch('{admin}/toggle-block', 'ActionController@toggleBlockedStatus')
            ->name('toggleBlock')->middleware('can:update,admin');
    });
});

Route::resource('services', 'ServiceController')
    ->only(['index', 'edit', 'update', 'destroy', 'create', 'store']);

Route::put('jobs/{job}/cancel', 'Job\ActionController@cancel')
    ->middleware('can:cancel,job')
    ->name('jobs.cancel');

Route::resource('jobs', 'JobController')
    ->only(['index', 'show']);

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([], base_path('routes/guest.php'));

// Realtor dashboard
Route::get('dashboard', 'DashboardController')->middleware(['auth', 'documents.verified'])
    ->name('dashboard');

// Realtor documents
Route::group(['prefix' => 'documents', 'as' => 'documents.', 'middleware' => ['auth']], function () {
    Route::get('/', 'DocumentController@create')->name('create');
    Route::post('store', 'DocumentController@store')->name('store')
        ->middleware('can:create,'.\App\Models\UserDocument::class);
    Route::get('{userDocument}', 'DocumentController@show')->name('show')
        ->middleware('can:view,userDocument');
});

// User account routes
Route::group(['prefix' => 'account', 'as' => 'account.', 'middleware' => ['auth']], function () {

    // My profile
    Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
        Route::get('/', 'Account\ProfileController@edit')->name('edit');

        Route::post('profile', 'Account\ProfileController@update')->name('updateProfile');
    });

    // Change password
    Route::group(['prefix' => 'password', 'as' => 'password.'], function () {
        Route::get('/', 'Account\PasswordController@edit')->name('edit');
        Route::post('update', 'Account\PasswordController@update')->name('update');
    });
});

// User profile
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'middleware' => ['auth']], function () {
    Route::get('{user}', 'ProfileController@show')->name('show');
});

// Job
Route::group(['prefix' => 'jobs', 'as' => 'jobs.', 'middleware' => ['auth', 'documents.verified']], function () {
    Route::get('{job}/detail', 'Job\ShowController@show')->name('show')
        ->middleware('can:view,job');
    Route::get('services', 'Job\CreateController@services')->name('services');
    Route::get('create/{service}', 'Job\CreateController@create')->name('create')
        ->middleware('can:create,'.App\Models\Job::class.',service');
    Route::post('create/{service}', 'Job\CreateController@store')->name('store')
        ->middleware('can:create,'.App\Models\Job::class.',service');
    Route::post('amount/{service}', 'Job\CreateController@getAmount')->name('amount')
        ->middleware('can:create,'.App\Models\Job::class.',service');
    Route::post('{job}/update', 'Job\CreateController@updateIncentive')->name('incentive.update');

    // Job assignment
    Route::group(['prefix' => '{job}/payments', 'as' => 'payments.'], function () {
        Route::get('assign/{user}', 'Job\AssignController@showAssignForm')
            ->name('assign')->middleware('can:assign,job,user');
        Route::post('assign/{user}', 'Job\AssignController@assign')
            ->middleware('can:assign,job,user');
    });

    // Job note
    Route::group(['prefix' => '{job}/chat', 'as' => 'chat.'], function () {
        Route::post('/', 'Job\ChatController@update')->name('update')
            ->middleware('can:update,'.\App\Models\JobChat::class.',job');
        Route::get('/', 'Job\ChatController@index')->name('index')
            ->middleware('can:view,'.\App\Models\JobChat::class.',job');
        Route::get('/{jobChat}/attachment', 'Job\ChatController@downloadAttachment')
            ->name('attachment')->middleware('can:view,'.\App\Models\JobChat::class.',job');
    });

    // Various actions on a Job
    Route::group(['prefix' => 'actions', 'as' => 'actions.'], function () {
        Route::post('{job}/accept', 'Job\ActionController@accept')
            ->name('accept')->middleware('can:accept,job');
        Route::delete('{job}', 'Job\ActionController@delete')
            ->name('destroy')->middleware('can:delete,job');
        Route::post('{job}/ignore', 'Job\ActionController@ignore')
            ->name('ignore');
        Route::post('{job}/done', 'Job\ActionController@markAsDone')
            ->name('done')->middleware('can:markAsDone,job');
        Route::post('{job}/complete', 'Job\ActionController@markAsCompleted')
            ->name('complete')->middleware('can:markAsCompleted,job');
    });
});

// Sent jobs
Route::group(['prefix' => 'sent-jobs', 'as' => 'sentJobs.', 'middleware' => ['auth', 'documents.verified']], function () {
    Route::get('sent', 'SentJobController@sent')->name('sent');
    Route::get('assigned', 'SentJobController@assigned')->name('assigned');
    Route::get('for-review', 'SentJobController@forReview')->name('forReview');
    Route::get('completed', 'SentJobController@completed')->name('completed');
});

// Received jobs
Route::group(['prefix' => 'received-jobs', 'as' => 'receivedJobs.', 'middleware' => ['auth', 'documents.verified']], function () {
    Route::get('received', 'ReceivedJobController@received')->name('received');
    Route::get('accepted', 'ReceivedJobController@accepted')->name('accepted');
    Route::get('to-do', 'ReceivedJobController@toDo')->name('toDo');
    Route::get('completed', 'ReceivedJobController@completed')->name('completed');
});

// Database Notifications
Route::group(['prefix' => 'notifications', 'as' => 'notifications.', 'middleware' => ['auth']], function () {
    Route::get('/', 'NotificationController@index')->name('index');
    Route::delete('delete-all', 'NotificationController@deleteAll')->name('deleteAll');

    Route::post('unread-all', 'NotificationController@markAllAsUnread')->name('markAllAsUnread');
    Route::post('{notification}/unread', 'NotificationController@markAsUnread')->name('markAsUnread');

    Route::post('read-all', 'NotificationController@markAllAsRead')->name('markAllAsRead');
    Route::post('{notification}/read', 'NotificationController@markAsRead')->name('markAsRead');
});

app/Models/Admin.php
<?php

namespace App\Models;

use App\Notifications\Admin\ResetPassword;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Admin extends Authenticatable
{
    use Notifiable;
    use HasFactory;

    protected $fillable = [
        'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'blocked_at' => 'datetime',
    ];

    public function setBlockedStatusTo($value)
    {
        $this->forceFill(['blocked_at' => $value]);
    }

    public function getIsBlockedAttribute($value)
    {
        return ! is_null($this->blocked_at);
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPassword($token));
    }
}

resources/views/admin/admins/_delete.blade.php
<form onsubmit="return confirm('Are you sure to delete this admin user?')"
      action="{{route('admin.admins.destroy',$admin)}}"
      method="POST">
  @csrf
  @method('delete')
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title text-danger">Delete admin</h5>

      <p class="card-text font-weight-light">
        This operation can't be undone.
      </p>
    </div>
    <div class="card-footer text-right">
      <button type="submit" class="btn btn-danger">
        <i class="fas fa-trash"></i> Delete admin
      </button>
    </div>
  </div>
</form>

resources/views/admin/admins/_passwordReset.blade.php
<form onsubmit="return confirm('Are you sure?')" action="{{route('admin.admins.actions.passwordResetEmail',$admin)}}"
      method="POST">
  @csrf
  <div class="card my-4">
    <div class="card-body">
      <h5 class="card-title">Send password reset e-mail</h5>
      <p class="card-text font-weight-light">
        An email with password reset instructions will be send to this user e-mail address.
      </p>
    </div>
    <div class="card-footer text-right">
      <button type="submit" class="btn btn-outline-primary">
        <i class="fas fa-envelope"></i> Send password reset e-mail
      </button>
    </div>
  </div>
</form>

resources/views/admin/admins/_updateBlockStatus.blade.php
<form onsubmit="return confirm('Are you sure?')"
      action="{{route('admin.admins.actions.toggleBlock',$admin)}}"
      method="POST">
  @csrf
  @method('patch')
  <div class="card mt-4">
    <div class="card-body">
      <h5 class="card-title">Block/unblock user</h5>
      <p class="card-text font-weight-light">
        When blocked; User will be logged out of all active devices and will not be allowed to log in back.
      </p>
    </div>
    <div class="card-footer text-right">
      @if($admin->is_blocked)
        <span class="text-muted mr-3">
                Blocked at
                @date($admin->blocked_at)
              </span>
        <button type="submit" class="btn btn-success"><i class="fas fa-lock-open"></i> Unblock</button>
      @else
        <button type="submit" class="btn btn-warning"><i class="fas fa-lock"></i> Block</button>
      @endif
    </div>
  </div>
</form>

resources/views/admin/admins/create.blade.php
@extends('admin._layouts.admin')
@section('pageTitle','Create broker')

@section('content')

  @component('admin.components.breadcrumb',[
       'links' => [
         'Admins' => route('admin.admins.index')
       ]
     ])
    Create admin
  @endcomponent

  @include('alert::bootstrap')

  <form method="POST" action="{{route('admin.admins.store')}}">
    {{csrf_field()}}

    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title">Create new admin user</h5>

        <div class="form-group required">
          <label for="email">E-Mail address</label>
          <input id="email" type="email" class="form-control @isInvalid('email')" name="email" placeholder="E-Mail"
                 value="{{old('email')}}"
                 required autofocus>
          @validationMessage('email')
        </div>
        <p class="card-text font-weight-light">User will receive an password reset email.</p>
      </div>
      <div class="card-footer text-right">
        <button type="submit" class="btn btn-primary">
          <i class="fas fa-check-circle"></i> Create admin
        </button>
      </div>
    </div>
  </form>

@endsection

resources/views/admin/admins/edit.blade.php
@extends('admin._layouts.admin')
@section('pageTitle','Edit Admin')

@section('content')

  @component('admin.components.breadcrumb',[
      'links' => [
        'Admins' => route('admin.admins.index')
      ]
    ])
    Edit admin
  @endcomponent

  @include('alert::bootstrap')

  <form method="POST" action="{{route('admin.admins.update',$admin)}}">
    @csrf
    @method('PUT')

    <section class="card mb-3">
      <div class="card-body">
        <h5 class="card-title">Edit admin</h5>

        <div class="form-group required">
          <label for="email">E-Mail address</label>
          <input id="email" type="email" class="form-control @isInvalid('email')" name="email" placeholder="E-Mail"
                 value="{{old('email',$admin->email)}}"
                 required autofocus>
          @validationMessage('email')
        </div>
        <p class="card-text font-weight-light">User will receive an password reset email on new email address.</p>
      </div>
      <div class="card-footer text-right">
        <button type="submit" class="btn btn-primary">
          <i class="fas fa-pencil-alt"></i> Update admin
        </button>
      </div>
    </section>
  </form>
  @include('admin.admins._passwordReset')
  @include('admin.admins._updateBlockStatus')
  @include('admin.admins._delete')
@endsection

resources/views/admin/admins/index.blade.php
@extends('admin._layouts.admin')
@section('pageTitle','Admins')

@section('content')

  <section class="row d-flex">
    <div class="col">
      @component('admin.components.breadcrumb')
        Admins
      @endcomponent
    </div>
    <div class="col pt-1 text-right">
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{{route('admin.admins.create')}}">
            <i class="fas fa-plus-circle"></i> Add new admin
          </a>
        </li>
      </ul>
    </div>
  </section>

  @include('alert::bootstrap')

  <section class="card mb-3">
    <div class="card-body">
      <form id="search-form" class="form-inline" method="GET" action="{{route('admin.admins.index')}}">
        <select class="form-control mb-2 mb-sm-0 mr-sm-2" name="per_page">
          <option disabled="">Per page</option>
          @foreach([10,30,50] as $perPage)
            <option value="{{$perPage}}"
                    @if(request('per_page') == $perPage) selected @endif>{{$perPage}}</option>
          @endforeach
        </select>

        <input type="text" class="form-control mb-2 mb-sm-0 mr-sm-2" placeholder="Search" name="search"
               value="{{request('search')}}" autofocus>

        <button type="submit" class="btn btn-primary mb-0 mb-sm-0 mr-sm-2">
          <i class="fa fa-search fa-fw"></i>Search
        </button>
      </form>
    </div>
  </section>

  <section class="table-responsive mb-3">
    <table class="table table-striped  table-bordered table-hover">
      <thead>
      <tr>
        <th>Email</th>
        <th>Created at</th>
        <th>Account Status</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      @forelse($admins as $admin)
        <tr>
          <td>{{$admin->email}}</td>
          <td>@date($admin->created_at)</td>
          <td class="align-middle h5">
            @if($admin->is_blocked)
              <span class="badge badge-danger">Blocked</span>
            @else
              <span class="badge badge-success">Active</span>
            @endif
          </td>
          <td class="text-center">
            <a href="{{route('admin.admins.edit',$admin)}}" class="btn btn-sm btn-outline-info mb-0">
              <i class="fa fa-edit"></i> Edit</a>
          </td>
        </tr>
      @empty
        <tr>
          <td colspan="6" class="text-center">No records found</td>
        </tr>
      @endforelse
      </tbody>
    </table>
  </section>

  @if($admins->total() > 0)
    <div class="row">
      <div class="col-md-4 mb-sm-0 mb-3 text-center text-sm-left">
        <h5 class="mt-sm-2 mt-0 mb-0">Found {{$admins->total()}} entries</h5>
      </div>
      <div class="col-md-8 d-flex">
        <div class="mx-auto ml-sm-auto mr-sm-0 table-responsive-sm">
          {{$admins->appends(request()->query())->links()}}
        </div>
      </div>
    </div>
  @endif
@endsection